### ISSUE TITLE
`v1.9.0` does not have the `dist/` files

### ISSUE THREAD

**Issue by yeled** [gr2m/create-or-update-pull-request-action#537]
`v1.9.0` does not have the `dist/` files, but they do exist in `v1.x`

_Originally posted by @gr2m in https://github.com/gr2m/create-or-update-pull-request-action/issues/500#issuecomment-1036384466_
      

Can we reinstate the dist/ files? v.1.4.1 seems to be the last release with it in.

Was it killed in ca7935b0e71523a753497fc5a5cbba3e73a411db?

My Actions Runners always seem to want it 
![image](https://user-images.githubusercontent.com/200421/196156332-1789aa8e-9446-4360-b176-44d09104392d.png)

**Comment by gr2m** [comment]
sorry I first thought this was an invalid issue. 

Having `/dist` in the default branch is a mess because it's causing merge conflicts all the time, that's why it only exists in [`v1`](https://github.com/gr2m/create-or-update-pull-request-action/tree/v1) and its `v1.x` alias

I agree this is not ideal but I also don't have the time to change that right now. There really is no elegant fix. Probably the best would be to use the `@semantic-release/git` plugin to push back the `dist/` files to the default branch as part of the release automation. We have that setup in https://github.com/twitter-together/action

**Comment by gdams** [comment]
I'm also seeing the same error here, is there any way this can be resolved?

**Comment by gr2m** [comment]
yes, same way we do it in https://github.com/twitter-together/action

> Probably the best would be to use the `@semantic-release/git` plugin to push back the `dist/` files to the default branch as part of the release automation. We have that setup in https://github.com/twitter-together/action

pull request welcome

**Comment by dreua** [comment]
The marketplace recommends version v1.5.1 which is obviously broken and wasted a good bit of my time. Can we gave this fixed? Otherwise I'd like to see a big warning in the Readme instructing to use 1.x.

Otherwise it works as expected, thank you for publishing it :)
